### ISSUE TITLE
New less organization

### ISSUE THREAD

**Issue by bouks** [openpsa/jsgrid#116]
I suggest we organize less files better, then we can change and/or optimize easily each part.
- one folder for each component (base, formedit, inlineedit, modal, subgrid, treegrid...)
- in each folder, separation of colors, fonts, positionning and sizes rules.

Here's a proposal (it can be improved)

https://github.com/bouks/jsgrid/tree/master/less_proposal

**Comment by meh-uk** [comment]
Doesn't this add complexity due to more files?

**Comment by bouks** [comment]
On the contrary, it is simpler when working css due to separation... maybe like Single Responsability or MVC patterns in coding.

**Comment by meh-uk** [comment]
That's fair, moving to 2.0 as I'd quite like to make a release :).

**Comment by bouks** [comment]
I think if we agree with this, we can implement now. There is no changes in the rules, on separation.
But need to adapt the build and why not the download builder to reduce css file size.

**Comment by bouks** [comment]
Fast and simple optimization :
https://github.com/bouks/jsgrid/commit/e9fed03be8fb67bf0948d5c6ec4af843c02f78f8

**Comment by flack** [comment]
I must admit I've never been a fan of the philosophy of separating CSS rules into different "roles" like colors, positioning etc. I've seen this used on some (mostly quite old) projects, but it always ended up making things more confusing.

Usually, people say that this makes e.g. theming easier, because all the font stuff and all the colors are in one place and so on. While this may be true, it does not apply to our situation for a number of reasons:

- we do not want people to customize the look by changing our CSS file. They should do their customizations in a separate file, to avoid problems when updating
- the standard CSS file we ship does not really define colors, fonts etc. anyways, but mostly uses `inherit` to get the correct ones from the jquery ui theme
- grouping rules by function is only necessary in CSS because it doesn't support variables. So you put all places that have the same color next to each other so that you don't miss one when changing it. With LESS, we don't need that workaround, because we can simply define the color (or font size, etc.) in a variable. Usually, all variables are in a file called `variables.less` (for example: https://github.com/twbs/bootstrap/blob/master/less/variables.less), which gives you one convenient place to change everything at once.

It is a matter of taste of course, but for me, having five different files named `pos.less` and potentially four different files where each selector is defined (`{color|font|pos|size}.less`) does not sound simpler to maintain

**Comment by flack** [comment]
To give you an example:

CSS separated by roles:

```css
/* color */
a
{
    color: red;
}
h1, p, button
{
    color: black
}
button
{
    border-color: black;
}

/* font */
a
{
    text-decoration: none;
}
h1, p, button
{
    font-family: Arial
}
```

The same in LESS with variables:
```less
/* define variables */
@link-color: red;
@default-color: black;
@default-font: Arial;

/* apply rules */
a
{
    color: @link-color;
    text-decoration: none;
}
h1, p, button
{
    color: @default-color;
    font-family: @default-font;
}
button
{
    border-color: @default-color;
}
```
